# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b4df5baea0f979a845da38568a68fe52b2461fa60715749c23741b98b339d6172575309118c45ba916bca5a855e05981af420d93477e4c6d6dfddc95798caaa

test:
  secret_key_base: 3378a5143ff04740194da859d7fb4b0057fca01aaaf3571666ad266c89d1a242086265731cf03373e8927ddaaac90e66d9999bcc91e72749c549ca707b764315

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
